[package]
name = "sandbox"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mrsoc-rt = { path = "../mrsoc-rt" }
riscv = "0.6.0"

[profile.release]
debug=true