[package]
name = "sandbox"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
mrsoc-rt = { path = "../mrsoc-rt" }

[profile.release]
debug=true